"""Configuration: one declarative layer for files, environment and plugin manifests."""

from __future__ import annotations

from manicule.config.loader import load_settings, save_settings
from manicule.config.profiles import PROFILES, ProfileConfig, profile_config
from manicule.config.providers import (
    DEFAULT_BASE_URLS,
    LOCAL_PROVIDERS,
    PROVIDER_ALIASES,
    ProviderSettings,
    env_var_names,
    is_local,
    resolve_provider_keys,
)
from manicule.config.settings import (
    APP_NAME,
    ENV_PREFIX,
    AuditDestination,
    AuditSettings,
    AuthMode,
    AuthSettings,
    ConnectorSettings,
    DataPolicySettings,
    EmbeddingSettings,
    EventSettings,
    LlmSettings,
    Mode,
    OAuthProvider,
    PluginSettings,
    RagSettings,
    RedactionMethod,
    RedactionSettings,
    Role,
    SecuritySettings,
    Settings,
    SourceRestrictions,
    StorageSettings,
    TelemetrySettings,
    Theme,
    TransportSettings,
    UiSettings,
    WebhookSettings,
    WorkspaceOverride,
    config_file,
    default_cache_dir,
    default_config_dir,
    default_data_dir,
)

__all__ = [
    "APP_NAME",
    "DEFAULT_BASE_URLS",
    "ENV_PREFIX",
    "LOCAL_PROVIDERS",
    "PROFILES",
    "PROVIDER_ALIASES",
    "AuditDestination",
    "AuditSettings",
    "AuthMode",
    "AuthSettings",
    "ConnectorSettings",
    "DataPolicySettings",
    "EmbeddingSettings",
    "EventSettings",
    "LlmSettings",
    "Mode",
    "OAuthProvider",
    "PluginSettings",
    "ProfileConfig",
    "ProviderSettings",
    "RagSettings",
    "RedactionMethod",
    "RedactionSettings",
    "Role",
    "SecuritySettings",
    "Settings",
    "SourceRestrictions",
    "StorageSettings",
    "TelemetrySettings",
    "Theme",
    "TransportSettings",
    "UiSettings",
    "WebhookSettings",
    "WorkspaceOverride",
    "config_file",
    "default_cache_dir",
    "default_config_dir",
    "default_data_dir",
    "env_var_names",
    "is_local",
    "load_settings",
    "profile_config",
    "resolve_provider_keys",
    "save_settings",
]
