"""Reading definitions out of text, and refusing prose that looks like one.

Two halves, and the second is the one that decides whether this feature is worth having. Any
regular expression finds ``NOW — Network Operations Workspace``; the question is whether the
same expression fills a glossary with every sentence containing a colon.
"""

from __future__ import annotations

import pytest

from manicule.core.content import Chunk, Document
from manicule.core.glossary import DefinitionForm, normalise_acronym, normalise_expansion
from manicule.ingest.glossary import (
    GLOSSARY_CONTEXT_EVIDENCE,
    INITIALS_EVIDENCE,
    MIN_DEFINITION_CONFIDENCE,
    acronym_shaped,
    detect_entries,
    detect_in_chunk,
    initials_match,
    score_definition,
)
from tests.storage_helpers import make_chunk, make_document

DOCUMENT = make_document(source_id="glossary", title="Glossary of terms")
PLAIN = make_document(source_id="handbook", title="Operations handbook")
EXPANSION = "Network Operations Workspace"


def chunk(
    text: str, *, document: Document = DOCUMENT, heading_path: tuple[str, ...] = ("Glossary",)
) -> Chunk:
    return make_chunk(document, 0, text, heading_path=heading_path)


# --- the forms the spec lists ---------------------------------------------------------------


@pytest.mark.parametrize(
    ("text", "form"),
    [
        (f"NOW — {EXPANSION}", DefinitionForm.EM_DASH),
        (f"NOW – {EXPANSION}", DefinitionForm.EM_DASH),  # noqa: RUF001 - an en dash, on purpose
        (f"NOW - {EXPANSION}", DefinitionForm.EM_DASH),
        (f"NOW: {EXPANSION}", DefinitionForm.COLON),
        (f"The {EXPANSION} (NOW) holds the runbooks.", DefinitionForm.PARENTHETICAL),
        (f"NOW\n: {EXPANSION}", DefinitionForm.DEFINITION_LIST),
        (f"| NOW | {EXPANSION} |", DefinitionForm.TABLE_ROW),
        (f"### NOW\n\n{EXPANSION}", DefinitionForm.HEADING),
    ],
    ids=[
        "em-dash",
        "en-dash",
        "spaced-hyphen",
        "colon",
        "parenthetical",
        "definition-list",
        "table-row",
        "heading",
    ],
)
def test_every_written_form_the_spec_names_is_detected(text: str, form: DefinitionForm) -> None:
    """``bugs/bug2.md`` §1, one case per bullet.

    Parametrised rather than written as one test with eight assertions, so a form that stops
    working is named in the failure rather than hidden behind whichever assertion ran first.
    """
    entries = detect_in_chunk(chunk(text))

    found = [entry for entry in entries if entry.acronym == "NOW"]
    assert found, f"{form.value} produced no entry from {text!r}"
    assert found[0].expansion == EXPANSION
    assert found[0].form is form
    assert found[0].chunk_id == chunk(text).id, "the entry must cite the chunk it came from"


def test_a_heading_lifted_into_the_breadcrumb_is_still_a_heading_definition() -> None:
    """The route the structural chunker actually takes.

    ``### NOW`` never reaches ``chunk.text`` once headings become the breadcrumb, so a detector
    reading only the text finds nothing on the corpus this feature exists for — while passing
    every test written against raw Markdown.
    """
    entries = detect_in_chunk(make_chunk(DOCUMENT, 0, EXPANSION, heading_path=("Glossary", "NOW")))

    assert [(entry.acronym, entry.form) for entry in entries] == [("NOW", DefinitionForm.HEADING)]


def test_a_term_written_with_dots_normalises_to_the_same_key() -> None:
    entries = detect_in_chunk(chunk(f"N.O.W. — {EXPANSION}"))

    assert [entry.acronym for entry in entries] == ["NOW"]
    assert entries[0].display == "N.O.W.", "the document's own spelling is what gets shown"


def test_a_parenthetical_listing_two_short_forms_records_the_second_as_an_alias() -> None:
    entries = detect_in_chunk(chunk(f"The {EXPANSION} (NOW, NETOPS) is where tickets live."))

    assert entries[0].acronym == "NOW"
    assert entries[0].aliases == ("NETOPS",)
    assert entries[0].keys == ("NOW", "NETOPS")


# --- refusing prose -------------------------------------------------------------------------


@pytest.mark.parametrize(
    "text",
    [
        "Note: the scheduler restarts nightly and the report lags by one cycle.",
        "Warning - do not edit this file by hand.",
        "Example: a document that has never been indexed.",
        "Tip — rotate the key before it expires.",
    ],
    ids=["note", "warning", "example", "tip"],
)
def test_prose_shaped_like_a_definition_is_refused(text: str) -> None:
    """The gate that does not negotiate.

    Every one of these has exactly the shape of a real definition — a capitalised word, a
    separator, a phrase. What refuses them is that the word is not *written* like an
    abbreviation, and no amount of glossary-looking context can buy that off.
    """
    assert detect_in_chunk(chunk(text)) == []


def test_a_glossary_page_does_not_admit_the_prose_inside_it() -> None:
    """The interaction that makes the two gates worth having separately.

    A page titled "Glossary" gives every line on it the context evidence, so a rule that
    weighed context alone would admit the sentence with a colon in it. The shape gate is what
    stops that, and this is the case where only the shape gate can.
    """
    text = f"NOW — {EXPANSION}\nNote: this list is reviewed each quarter."

    entries = detect_in_chunk(chunk(text), glossary_context=True)

    assert [entry.acronym for entry in entries] == ["NOW"]


@pytest.mark.parametrize(
    "expansion",
    [
        "a workspace where the network operations team keeps every runbook it owns today",
        "Network Operations Workspace. It replaced three spreadsheets",
    ],
    ids=["too-long", "more-than-one-sentence"],
)
def test_an_expansion_that_is_really_a_sentence_is_refused(expansion: str) -> None:
    assert detect_in_chunk(chunk(f"NOW — {expansion}")) == []


def test_a_term_defined_as_itself_is_not_a_definition() -> None:
    assert detect_in_chunk(chunk("NOW — NOW")) == []


def test_a_table_rule_row_is_not_a_definition() -> None:
    text = "| Term | Meaning |\n|------|---------|\n| NOW | " + EXPANSION + " |"

    assert [entry.acronym for entry in detect_in_chunk(chunk(text))] == ["NOW"]


# --- the confidence, and what it is made of ---------------------------------------------------


def test_initials_are_matched_with_and_without_the_small_words() -> None:
    """``ATLAS`` spells out its ``And``; ``RAM`` skips its ``of``. Nothing says which."""
    assert initials_match("ATLAS", "Automated Transfer Ledger And Scheduler")
    assert initials_match("RAM", "Random Access of Memory")
    assert not initials_match("NOW", "Nightly Operations")


@pytest.mark.parametrize(
    ("surface", "shaped"),
    [
        ("NOW", True),
        ("N.O.W.", True),
        ("IPv6", True),
        ("Note", False),
        ("Warning", False),
        ("A", False),
    ],
)
def test_only_abbreviation_shaped_terms_pass_the_shape_gate(surface: str, shaped: bool) -> None:
    assert acronym_shaped(surface) is shaped


def test_the_dash_form_clears_the_threshold_on_its_initials_alone() -> None:
    """Stated as arithmetic, because the threshold was set from these combinations.

    A test asserting only "it is detected" would pass if the threshold moved to zero.
    """
    score = score_definition("NOW", EXPANSION, DefinitionForm.EM_DASH, glossary_context=False)

    assert score >= MIN_DEFINITION_CONFIDENCE
    assert score == pytest.approx(0.45 + INITIALS_EVIDENCE)


def test_a_colon_form_with_neither_piece_of_evidence_does_not_clear_it() -> None:
    score = score_definition(
        "ABC", "Nightly Operations Report", DefinitionForm.COLON, glossary_context=False
    )

    assert score < MIN_DEFINITION_CONFIDENCE


def test_glossary_context_alone_cannot_admit_a_colon_form() -> None:
    """The smallest of the three pieces of evidence, and it must stay too small to decide.

    A page can be a glossary and still contain a sentence with a colon in it, so context has to
    be worth less than the gap between the colon form and the threshold.
    """
    score = score_definition(
        "ABC", "Nightly Operations Report", DefinitionForm.COLON, glossary_context=True
    )

    assert GLOSSARY_CONTEXT_EVIDENCE > 0.0
    assert score < MIN_DEFINITION_CONFIDENCE


def test_a_document_titled_glossary_lifts_a_form_that_carries_nothing_else() -> None:
    """Detection reads the *document's* title, which a chunk does not carry."""
    text = "FATHOM — Failure Analysis Tooling Home"
    on_a_glossary = detect_entries([chunk(text, document=DOCUMENT)], title="Glossary of terms")
    elsewhere = detect_entries(
        [chunk(text, document=PLAIN, heading_path=("Runbook",))], title="Operations handbook"
    )

    assert [entry.acronym for entry in on_a_glossary] == ["FATHOM"]
    assert elsewhere == [], "the same line in a runbook has neither piece of evidence"


# --- normalisation ----------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("surface", "key"),
    [
        ("NOW", "NOW"),
        ("now", "NOW"),
        ("NOW?", "NOW"),
        ("(NOW)", "NOW"),
        ("N.O.W.", "NOW"),
        ("“NOW”", "NOW"),
        ("N", ""),
        ("", ""),
        ("supercalifragilistic", ""),
    ],
)
def test_a_surface_form_normalises_to_one_key(surface: str, key: str) -> None:
    """Query time and ingest time must agree exactly, so there is one function and one test."""
    assert normalise_acronym(surface) == key


def test_two_expansions_are_the_same_only_when_they_say_the_same_thing() -> None:
    """Case and spacing are noise; word order is a different claim.

    Normalising word order away would silently merge two definitions that disagree, which is
    the one thing this feature must never do quietly.
    """
    assert normalise_expansion("Network Operations Workspace") == normalise_expansion(
        "network   operations workspace."
    )
    assert normalise_expansion("Network Operations Workspace") != normalise_expansion(
        "Workspace, Network Operations"
    )
