"""Shell completion, generated by Typer rather than written out by hand.

The script does not enumerate commands: it calls ``manicule`` back with a marker variable set
and lets the live command tree answer. So a command added tomorrow completes tomorrow, with no
regenerated file to remember — which is the failure a hand-written completion script always
eventually has.
"""

from __future__ import annotations

# `_completion_shared` is where Typer keeps this and where its own `--show-completion`
# reads it from; the re-export on `typer.completion` is not declared public. Importing
# the module that owns it is the honest form of the same dependency.
from typer._completion_shared import Shells, get_completion_script

from manicule.core.errors import ConfigError

COMPLETE_VAR = "_MANICULE_COMPLETE"
"""The variable the generated script sets when it asks the program for completions."""

PROGRAM_NAME = "manicule"

SHELLS: tuple[str, ...] = tuple(shell.value for shell in Shells)


def completion_script(shell: str) -> str:
    """The completion script for one shell.

    Raises:
        ConfigError: Typer has no completion support for that shell. The message lists the
            ones it does have, because the usual cause is a typo.
    """
    chosen = shell.strip().lower()
    if chosen not in SHELLS:
        available = ", ".join(SHELLS)
        msg = f"no completion support for shell {shell!r}. Available: {available}"
        raise ConfigError(msg)
    return get_completion_script(prog_name=PROGRAM_NAME, complete_var=COMPLETE_VAR, shell=chosen)


__all__ = ["COMPLETE_VAR", "PROGRAM_NAME", "SHELLS", "completion_script"]
