"""Migrations, and the two checks that keep them honest.

These are the enforcement half of #18. Without them, a model edited without a migration and a
downgrade that has never run both look exactly like a healthy repository.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
from alembic.autogenerate import compare_metadata
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import text

from manicule.storage.autogen import include_name, include_object
from manicule.storage.engine import create_engine
from manicule.storage.fts import FTS_SHADOW_TABLES
from manicule.storage.migrator import alembic_config, current, downgrade, head_revision, upgrade
from manicule.storage.models import Base

if TYPE_CHECKING:
    from pathlib import Path

    from sqlalchemy.engine import Connection
    from sqlalchemy.ext.asyncio import AsyncEngine


def _diff(connection: Connection) -> list[object]:
    context = MigrationContext.configure(
        connection,
        opts={
            "compare_type": True,
            "compare_server_default": True,
            "include_name": include_name,
            "include_object": include_object,
            "target_metadata": Base.metadata,
        },
    )
    return list(compare_metadata(context, Base.metadata))


@pytest.mark.contract
async def test_the_models_and_the_migrations_agree(engine: AsyncEngine) -> None:
    """``alembic check``, as a test.

    A model edited without a migration produces a schema that exists only in the developer's
    working tree; the first fresh database finds the columns missing.
    """
    async with engine.connect() as connection:
        differences = await connection.run_sync(_diff)
    assert differences == [], (
        f"the models have drifted from the migrations: {differences}. "
        f"Generate a revision with `uv run alembic revision --autogenerate`."
    )


@pytest.mark.contract
async def test_every_revision_downgrades_and_upgrades_back_to_the_same_schema(
    data_dir: Path,
) -> None:
    """A downgrade that has never run is not a downgrade path.

    It is untested code that will be needed exactly once, under pressure. This matters more
    on SQLite than elsewhere: batch mode implements every constraint change as
    create-copy-swap, and a batch downgrade that cannot name the constraint it drops fails in
    a way only running it reveals.
    """
    script = ScriptDirectory.from_config(alembic_config())
    revisions = [revision.revision for revision in script.walk_revisions()]

    engine = create_engine(data_dir)
    try:
        await upgrade(engine)
        assert await current(engine) == head_revision()
        before = await _schema_snapshot(engine)

        for revision in revisions:
            down_to = script.get_revision(revision).down_revision or "base"
            await downgrade(engine, down_to if isinstance(down_to, str) else "base")
            await upgrade(engine)

        assert await current(engine) == head_revision()
        assert await _schema_snapshot(engine) == before, (
            "the schema after a downgrade/upgrade round trip differs from the schema before it"
        )
    finally:
        await engine.dispose()


async def test_downgrading_to_base_leaves_nothing_of_ours_behind(data_dir: Path) -> None:
    """A downgrade that leaves tables behind makes the next upgrade fail on a fresh start."""
    engine = create_engine(data_dir)
    try:
        await upgrade(engine)
        await downgrade(engine, "base")
        async with engine.connect() as connection:
            names = set(
                (
                    await connection.execute(
                        text("SELECT name FROM sqlite_master WHERE type='table'")
                    )
                )
                .scalars()
                .all()
            )
        assert "documents" not in names
        assert "chunks_fts" not in names, "the virtual table must be dropped with the rest"
        assert not any(name.startswith("chunks_fts") for name in names)
    finally:
        await engine.dispose()


def test_autogenerate_never_proposes_dropping_the_lexical_index() -> None:
    """Alembic does not model virtual tables, so it sees them as tables to remove.

    Without this filter every autogenerated revision begins by deleting the FTS index and its
    five shadow tables.
    """
    for name in FTS_SHADOW_TABLES:
        assert not include_name(name, "table", {})
        assert not include_object(Base.metadata, name, "table", True, None)
    assert include_name("documents", "table", {})
    assert include_name("id", "column", {})


def test_every_constraint_has_a_name_a_migration_can_refer_to() -> None:
    """Batch mode must *name* the constraint it drops, and SQLite generates anonymous ones.

    A project that discovers this later cannot write the migration it needs.
    """
    unnamed: list[str] = []
    for table in Base.metadata.sorted_tables:
        for constraint in table.constraints:
            if constraint.name is None or str(constraint.name).startswith("_unnamed_"):
                unnamed.append(f"{table.name}.{type(constraint).__name__}")
        for index in table.indexes:
            if index.name is None:
                unnamed.append(f"{table.name}.Index")
    assert unnamed == []


async def _schema_snapshot(engine: AsyncEngine) -> list[tuple[str, str]]:
    """Every object the schema declares, as text, ordered.

    Comparing the SQL rather than a reflection because a round trip that silently drops a
    ``CHECK`` still reflects as a table with the right columns.
    """
    async with engine.connect() as connection:
        rows = (
            await connection.execute(
                text(
                    "SELECT type, name, COALESCE(sql, '') FROM sqlite_master "
                    "WHERE name NOT LIKE 'sqlite_%' AND name <> 'alembic_version' "
                    "ORDER BY type, name"
                )
            )
        ).all()
    return [(f"{row[0]}:{row[1]}", " ".join(str(row[2]).split())) for row in rows]
