"""Core: the types and protocols everything else is written against.

Core carries no implementation dependencies. Importing it must not pull in a vector store,
a model runtime, an HTTP framework or an inference library — that boundary is what lets a
plugin author depend on manicule's contracts without inheriting its stack, and it is
enforced by a test rather than by convention.
"""

from __future__ import annotations

from manicule.core.anchors import (
    EDGE_TOLERANCE,
    Anchor,
    CellAnchor,
    HeadingAnchor,
    LineAnchor,
    PageAnchor,
    Rect,
    Unlocated,
    is_located,
)
from manicule.core.content import (
    CHUNKLESS_BY_DESIGN,
    IN_FLIGHT,
    NEEDS_ATTENTION,
    SETTLED,
    BlockKind,
    Chunk,
    Document,
    DocumentStatus,
    Metadata,
    ParsedBlock,
    PipelineStage,
    RawDocument,
    Retention,
)
from manicule.core.embedding import (
    EmbedFingerprint,
    NDArrayLike,
    Pooling,
    TokenStates,
    Vector,
    require_within_context,
)
from manicule.core.errors import (
    ChunkingError,
    CircularDependencyError,
    ConfigError,
    ContainerError,
    ContainerStateError,
    ContextOverflowError,
    DuplicateComponentError,
    FingerprintMismatchError,
    IncompatiblePluginError,
    ManiculeError,
    ParseError,
    PluginDependencyError,
    PluginError,
    PluginLoadError,
    PolicyError,
    UnknownComponentError,
)
from manicule.core.fingerprints import ChunkFingerprint, Fingerprint
from manicule.core.generation import FinishReason, Token, Usage
from manicule.core.ids import chunk_id, content_hash, document_id
from manicule.core.lifecycle import (
    HealthCheck,
    HealthReport,
    HealthState,
    Lifecycle,
    Metric,
    SupportsHealth,
    SupportsMetrics,
    SupportsSetup,
    SupportsTeardown,
    worst_state,
)
from manicule.core.protocols import (
    Chunker,
    Connector,
    DocStore,
    Embedder,
    Generator,
    Middleware,
    Parser,
    Reranker,
    RetrievalStage,
    TokenStateEmbedder,
    VectorStore,
)
from manicule.core.retrieval import Candidate, Context, Filter, Query, RetrievalProfile
from manicule.core.sources import DiscoveredDoc, DocRef, SourceId, Watermark
from manicule.core.version import CORE_VERSION

__all__ = [
    "CHUNKLESS_BY_DESIGN",
    "CORE_VERSION",
    "EDGE_TOLERANCE",
    "IN_FLIGHT",
    "NEEDS_ATTENTION",
    "SETTLED",
    "Anchor",
    "BlockKind",
    "Candidate",
    "CellAnchor",
    "Chunk",
    "ChunkFingerprint",
    "Chunker",
    "ChunkingError",
    "CircularDependencyError",
    "ConfigError",
    "Connector",
    "ContainerError",
    "ContainerStateError",
    "Context",
    "ContextOverflowError",
    "DiscoveredDoc",
    "DocRef",
    "DocStore",
    "Document",
    "DocumentStatus",
    "DuplicateComponentError",
    "EmbedFingerprint",
    "Embedder",
    "Filter",
    "Fingerprint",
    "FingerprintMismatchError",
    "FinishReason",
    "Generator",
    "HeadingAnchor",
    "HealthCheck",
    "HealthReport",
    "HealthState",
    "IncompatiblePluginError",
    "Lifecycle",
    "LineAnchor",
    "ManiculeError",
    "Metadata",
    "Metric",
    "Middleware",
    "NDArrayLike",
    "PageAnchor",
    "ParseError",
    "ParsedBlock",
    "Parser",
    "PipelineStage",
    "PluginDependencyError",
    "PluginError",
    "PluginLoadError",
    "PolicyError",
    "Pooling",
    "Query",
    "RawDocument",
    "Rect",
    "Reranker",
    "Retention",
    "RetrievalProfile",
    "RetrievalStage",
    "SourceId",
    "SupportsHealth",
    "SupportsMetrics",
    "SupportsSetup",
    "SupportsTeardown",
    "Token",
    "TokenStateEmbedder",
    "TokenStates",
    "UnknownComponentError",
    "Unlocated",
    "Usage",
    "Vector",
    "VectorStore",
    "Watermark",
    "chunk_id",
    "content_hash",
    "document_id",
    "is_located",
    "require_within_context",
    "worst_state",
]
