"""initial schema

Revision ID: 2674752edf52
Revises:
Created: 2026-08-10 09:01:03.822162
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import manicule.storage.types
from manicule.storage.fts import CREATE_FTS, CREATE_TRIGGERS, DROP_TRIGGERS, FTS_TABLE

revision: str = "2674752edf52"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column("created_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_audit_logs_event_type_created_at", ["event_type", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_audit_logs_workspace_id_created_at", ["workspace_id", "created_at"], unique=False
        )

    op.create_table(
        "blobs",
        sa.Column("hash", sa.Text(), nullable=False),
        sa.Column("algo", sa.Text(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("stored_bytes", sa.Integer(), nullable=False),
        sa.Column("compression", sa.Text(), nullable=False),
        sa.Column("created_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "size_bytes >= 0 AND stored_bytes >= 0", name=op.f("ck_blobs_sizes_are_not_negative")
        ),
        sa.PrimaryKeyConstraint("hash", name=op.f("pk_blobs")),
    )
    op.create_table(
        "index_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vector_table", sa.Text(), nullable=True),
        sa.Column("embed_fingerprint", sa.Text(), nullable=True),
        sa.Column("chunk_fingerprint", sa.Text(), nullable=True),
        sa.Column("fts_tokenizer", sa.Text(), nullable=True),
        sa.Column("created_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.Column("updated_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_index_state_is_a_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_state")),
    )
    op.create_table(
        "plugins",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("installed_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_plugins")),
    )
    op.create_table(
        "vector_tombstones",
        sa.Column("chunk_id", sa.Text(), nullable=False),
        sa.Column("deleted_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("chunk_id", name=op.f("pk_vector_tombstones")),
        sqlite_with_rowid=False,
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("created_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "mode IN ('personal', 'team')", name=op.f("ck_workspaces_mode_is_known")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
        sa.UniqueConstraint("name", name=op.f("uq_workspaces_name")),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("key_prefix", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("allowed_ips", sa.JSON(), nullable=False),
        sa.Column("rate_limit", sa.Integer(), nullable=True),
        sa.Column("expires_at", manicule.storage.types.UtcDateTime(), nullable=True),
        sa.Column("last_used_at", manicule.storage.types.UtcDateTime(), nullable=True),
        sa.Column("revoked_at", manicule.storage.types.UtcDateTime(), nullable=True),
        sa.Column("created_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "role IN ('admin', 'member', 'viewer')", name=op.f("ck_api_keys_role_is_known")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_api_keys_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index("ix_api_keys_workspace_id", ["workspace_id"], unique=False)

    op.create_table(
        "collections",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("auto_rules", sa.JSON(), nullable=True),
        sa.Column("created_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_collections_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
        sa.UniqueConstraint("workspace_id", "name", name="uq_collections_ws_name"),
    )
    op.create_table(
        "connectors",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("watermark", sa.JSON(), nullable=True),
        sa.Column("sync_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("last_synced_at", manicule.storage.types.UtcDateTime(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("deleted_at", manicule.storage.types.UtcDateTime(), nullable=True),
        sa.Column("created_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_connectors_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connectors")),
    )
    with op.batch_alter_table("connectors", schema=None) as batch_op:
        batch_op.create_index(
            "uq_connectors_workspace_id_name",
            ["workspace_id", "name"],
            unique=True,
            sqlite_where=sa.text("deleted_at IS NULL"),
        )

    op.create_table(
        "conversations",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("shared", sa.Boolean(), nullable=False),
        sa.Column("share_token", sa.Text(), nullable=True),
        sa.Column("deleted_at", manicule.storage.types.UtcDateTime(), nullable=True),
        sa.Column("created_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.Column("updated_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_conversations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("share_token", name=op.f("uq_conversations_share_token")),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("uri", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("version_token", sa.Text(), nullable=True),
        sa.Column("original_ref", sa.Text(), nullable=True),
        sa.Column("original_omitted_reason", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "parsed",
                "indexed",
                "container",
                "no_extractable_text",
                "unsupported_media_type",
                "failed",
                "skipped",
                "deleted",
                name="document_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("status_detail", sa.Text(), nullable=True),
        sa.Column(
            "failed_stage",
            sa.Enum(
                "discover",
                "fetch",
                "parse",
                "chunk",
                "embed",
                "store",
                name="pipeline_stage",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("chunk_fp", sa.Text(), nullable=True),
        sa.Column("embed_fp", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.Column("updated_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.Column("indexed_at", manicule.storage.types.UtcDateTime(), nullable=True),
        sa.Column("last_seen_at", manicule.storage.types.UtcDateTime(), nullable=True),
        sa.Column("deleted_at", manicule.storage.types.UtcDateTime(), nullable=True),
        sa.CheckConstraint(
            "(status = 'failed') = (failed_stage IS NOT NULL)",
            name=op.f("ck_documents_failed_stage_iff_failed"),
        ),
        sa.ForeignKeyConstraint(
            ["original_ref"],
            ["blobs.hash"],
            name=op.f("fk_documents_original_ref_blobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_documents_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index("ix_documents_chunk_fp", ["chunk_fp"], unique=False)
        batch_op.create_index("ix_documents_content_hash", ["content_hash"], unique=False)
        batch_op.create_index(
            "ix_documents_deleted_at",
            ["workspace_id", "deleted_at"],
            unique=False,
            sqlite_where=sa.text("deleted_at IS NOT NULL"),
        )
        batch_op.create_index("ix_documents_embed_fp", ["embed_fp"], unique=False)
        batch_op.create_index(
            "ix_documents_workspace_id_status", ["workspace_id", "status"], unique=False
        )
        batch_op.create_index(
            "ix_documents_workspace_id_uri", ["workspace_id", "uri"], unique=False
        )
        batch_op.create_index(
            "uq_documents_identity",
            ["workspace_id", "source", "source_id"],
            unique=True,
            sqlite_where=sa.text("deleted_at IS NULL"),
        )

    op.create_table(
        "query_logs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("profile", sa.Text(), nullable=True),
        sa.Column("retrieved_chunk_ids", sa.JSON(), nullable=True),
        sa.Column("reranked_chunk_ids", sa.JSON(), nullable=True),
        sa.Column("retrieval_score_avg", sa.Float(), nullable=True),
        sa.Column("rerank_score_avg", sa.Float(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("created_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_query_logs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_query_logs")),
    )
    with op.batch_alter_table("query_logs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_query_logs_workspace_id_created_at", ["workspace_id", "created_at"], unique=False
        )

    op.create_table(
        "tags",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_tags_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("workspace_id", "name", name="uq_tags_workspace_id_name"),
    )
    op.create_table(
        "workspace_members",
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("created_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "role IN ('admin', 'member', 'viewer')", name=op.f("ck_workspace_members_role_is_known")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workspace_members_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("workspace_id", "user_id", name=op.f("pk_workspace_members")),
        sqlite_with_rowid=False,
    )
    op.create_table(
        "chunks",
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("document_id", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embed_text", sa.Text(), nullable=False),
        sa.Column("heading_text", sa.Text(), nullable=False),
        sa.Column("heading_path", sa.JSON(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "prose",
                "heading",
                "table",
                "code",
                "list",
                "panel",
                "media",
                name="block_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("lang", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("anchor", sa.JSON(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "position >= 0 AND token_count >= 0", name=op.f("ck_chunks_counts_are_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_chunks")),
        sa.UniqueConstraint("document_id", "position", name="uq_chunks_document_id_position"),
        sa.UniqueConstraint("id", name=op.f("uq_chunks_id")),
    )
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.create_index("ix_chunks_kind", ["kind"], unique=False)

    op.create_table(
        "collection_documents",
        sa.Column("collection_id", sa.Text(), nullable=False),
        sa.Column("document_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_collection_documents_collection_id_collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_collection_documents_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "collection_id", "document_id", name=op.f("pk_collection_documents")
        ),
        sqlite_with_rowid=False,
    )
    op.create_table(
        "document_tags",
        sa.Column("document_id", sa.Text(), nullable=False),
        sa.Column("tag_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_tags_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_document_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("document_id", "tag_id", name=op.f("pk_document_tags")),
        sqlite_with_rowid=False,
    )
    op.create_table(
        "document_versions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("document_id", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("original_ref", sa.Text(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=True),
        sa.Column("changes", sa.JSON(), nullable=True),
        sa.Column("created_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_versions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["original_ref"],
            ["blobs.hash"],
            name=op.f("fk_document_versions_original_ref_blobs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint(
            "document_id", "version", name="uq_document_versions_document_id_version"
        ),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("conversation_id", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=True),
        sa.Column("profile_used", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", manicule.storage.types.UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "role IN ('user', 'assistant', 'system')", name=op.f("ck_messages_role_is_known")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_messages_conversation_id_created_at",
            ["conversation_id", "created_at"],
            unique=False,
        )

    op.create_table(
        "chunk_relations",
        sa.Column("source_chunk_id", sa.Text(), nullable=False),
        sa.Column("target_chunk_id", sa.Text(), nullable=False),
        sa.Column("relation_type", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "source_chunk_id <> target_chunk_id", name=op.f("ck_chunk_relations_no_self_relation")
        ),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"],
            ["chunks.id"],
            name=op.f("fk_chunk_relations_source_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_chunk_id"],
            ["chunks.id"],
            name=op.f("fk_chunk_relations_target_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "source_chunk_id", "target_chunk_id", "relation_type", name=op.f("pk_chunk_relations")
        ),
        sqlite_with_rowid=False,
    )
    with op.batch_alter_table("chunk_relations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_chunk_relations_target_chunk_id", ["target_chunk_id"], unique=False
        )

    _create_lexical_index()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_lexical_index()
    with op.batch_alter_table("chunk_relations", schema=None) as batch_op:
        batch_op.drop_index("ix_chunk_relations_target_chunk_id")

    op.drop_table("chunk_relations")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_messages_conversation_id_created_at")

    op.drop_table("messages")
    op.drop_table("document_versions")
    op.drop_table("document_tags")
    op.drop_table("collection_documents")
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.drop_index("ix_chunks_kind")

    op.drop_table("chunks")
    op.drop_table("workspace_members")
    op.drop_table("tags")
    with op.batch_alter_table("query_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_query_logs_workspace_id_created_at")

    op.drop_table("query_logs")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index("uq_documents_identity", sqlite_where=sa.text("deleted_at IS NULL"))
        batch_op.drop_index("ix_documents_workspace_id_uri")
        batch_op.drop_index("ix_documents_workspace_id_status")
        batch_op.drop_index("ix_documents_embed_fp")
        batch_op.drop_index(
            "ix_documents_deleted_at", sqlite_where=sa.text("deleted_at IS NOT NULL")
        )
        batch_op.drop_index("ix_documents_content_hash")
        batch_op.drop_index("ix_documents_chunk_fp")

    op.drop_table("documents")
    op.drop_table("conversations")
    with op.batch_alter_table("connectors", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_connectors_workspace_id_name", sqlite_where=sa.text("deleted_at IS NULL")
        )

    op.drop_table("connectors")
    op.drop_table("collections")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index("ix_api_keys_workspace_id")

    op.drop_table("api_keys")
    op.drop_table("workspaces")
    op.drop_table("vector_tombstones")
    op.drop_table("plugins")
    op.drop_table("index_state")
    op.drop_table("blobs")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_logs_workspace_id_created_at")
        batch_op.drop_index("ix_audit_logs_event_type_created_at")

    op.drop_table("audit_logs")
    # ### end Alembic commands ###


def _create_lexical_index() -> None:
    """Create the FTS5 index over ``chunks`` and the triggers that maintain it.

    Hand-written because Alembic models neither virtual tables nor triggers. The triggers are
    what make the lexical index impossible to bypass: they run inside the same transaction as
    the row change, so a write path nobody remembered still updates the index.
    """
    op.execute(CREATE_FTS)
    for statement in CREATE_TRIGGERS:
        op.execute(statement)


def _drop_lexical_index() -> None:
    """Drop the triggers before the table they write to."""
    for statement in DROP_TRIGGERS:
        op.execute(statement)
    op.execute(f"DROP TABLE IF EXISTS {FTS_TABLE}")
