#!/usr/bin/env python
"""Build an offline tree-sitter grammar bundle for an air-gapped install.

Run this on a machine that *has* network access and the same platform as the target. It
pre-seeds the declared language set, copies each grammar library into a bundle directory,
records the pack release, the platform and a SHA-256 per library, and asserts that the pack's
licence is one manicule may redistribute.

    python tools/build_grammar_bundle.py --output dist/grammars

The result is a directory. Copy it to the air-gapped host and point manicule at it:

    MANICULE_GRAMMAR_BUNDLE=/opt/manicule/grammars

or build it straight into a distribution that ships the bundle as package data:

    python tools/build_grammar_bundle.py --output build/pkg --package

which writes an importable ``manicule_grammars`` package — the ``manicule[grammars-offline]``
shape, where the grammars travel through the same channel as every other dependency and no
environment variable is needed at all.

**Why a bundle and not the two alternatives.** Building grammars at install time was rejected
on sight: it needs a C toolchain on the user's machine, and the API for it was removed from
``py-tree-sitter`` at 0.22. Pointing the pack's manifest URL at an internal mirror works and
assumes somebody has a mirror, which is exactly the assumption an air-gapped site cannot make.
A directory of files assumes only that the install itself got there.

**Never downloads on your behalf while building.** ``--prefetch`` fetches first and is a
separate, explicit step, so a bundle cannot half-build against a flaky mirror and silently
omit a language. Without it the build reads a cache that is already populated and fails naming
anything absent.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from manicule.core.errors import ManiculeError
from manicule.parsers import grammar_bundle, grammars

PACKAGE_INIT = '''"""Offline tree-sitter grammars for manicule, as package data.

Generated by ``tools/build_grammar_bundle.py``. The bundle beside this module is platform- and
release-specific: it is valid for one operating system, one architecture and one
``tree-sitter-language-pack`` release, and manicule refuses it loudly on any other rather than
loading libraries built for something else.
"""

from pathlib import Path

__all__ = ["bundle_root"]


def bundle_root() -> Path:
    """The bundle directory carried by this distribution."""
    return Path(__file__).parent / "bundle"
'''


def main(argv: list[str] | None = None) -> int:
    """Build the bundle. Returns a process exit status."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Directory to write the bundle into. Created if absent.",
    )
    parser.add_argument(
        "--languages",
        nargs="+",
        default=list(grammars.DECLARED_LANGUAGES),
        help="Languages to bundle. Defaults to manicule's declared set, which is what an "
        "install needs; a narrower set makes a smaller bundle and a host that refuses "
        "everything outside it.",
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=None,
        help="A populated grammar cache to copy from. Defaults to this machine's.",
    )
    parser.add_argument(
        "--prefetch",
        action="store_true",
        help="Fetch anything missing from the cache first. Requires network access, and is "
        "opt-in so that a build cannot quietly become a download.",
    )
    parser.add_argument(
        "--package",
        action="store_true",
        help="Write an importable manicule_grammars package around the bundle, so it can be "
        "installed rather than copied.",
    )
    args = parser.parse_args(argv)

    languages: list[str] = list(args.languages)
    try:
        if args.prefetch:
            seeded = grammars.prefetch(languages)
            print(f"seeded: {list(seeded)}")
        source = Path(args.source) if args.source is not None else grammars.cache_directory()
        destination = Path(args.output)
        if args.package:
            destination = destination / "src" / grammar_bundle.BUNDLE_MODULE / "bundle"
        bundle = grammar_bundle.build(languages, destination, source=source)
        if args.package:
            module = destination.parent
            (module / "__init__.py").write_text(PACKAGE_INIT, encoding="utf-8")
            (module / "py.typed").write_text("", encoding="utf-8")
    except ManiculeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    total = sum(entry.size for entry in bundle.grammars.values())
    print(f"bundle:   {bundle.root}")
    print(f"pack:     tree-sitter-language-pack {bundle.pack_version}")
    print(f"platform: {bundle.platform}")
    print(f"licence:  {bundle.licence} (asserted redistributable)")
    print(f"size:     {total / 1_000_000:.1f} MB across {len(bundle.languages)} languages")
    for language in bundle.languages:
        entry = bundle.grammars[language]
        print(f"  {language:<12} {entry.filename:<36} {entry.sha256[:16]} {entry.size:>10}")
    return 0


if __name__ == "__main__":  # pragma: no cover - a script entry point
    raise SystemExit(main())
