#!/usr/bin/env python
"""Build an offline tiktoken vocabulary bundle for an air-gapped install.

Run this on a machine that *has* network access. It pre-seeds the encodings manicule asks for,
copies each vocabulary file out of the tiktoken cache into a bundle directory, and records the
URL, size and SHA-256 of every one — the digest being the one tiktoken itself declares, so a
bundle cannot carry the wrong bytes under the right name.

    python tools/build_vocabulary_bundle.py --output dist/vocabularies

The result is a directory. Copy it to the air-gapped host and point manicule at it:

    MANICULE_VOCABULARY_BUNDLE=/opt/manicule/vocabularies

or build it straight into a distribution that ships the bundle as package data:

    python tools/build_vocabulary_bundle.py --output build/pkg --package

which writes an importable ``manicule_vocabularies`` package, so the vocabularies travel
through the same channel as every other dependency and no environment variable is needed at
all.

**Why this exists rather than a file in manicule's own wheel.** ``tiktoken`` publishes no
vocabularies in its wheel; they come from a Microsoft-hosted blob store on first use. manicule
does not redistribute them either, and the reason is worth stating plainly: OpenAI publishes
those files with no SPDX license expression, so manicule cannot describe the terms under which
it would be handing them on. A bundle is built and carried by the operator who has decided
that question for their own site, and the manifest records the URL every file came from so
that decision can be made with the facts in front of them.

**The unit is 5 MB, not 5 GB.** ``cl100k_base`` is 1.7 MB and ``o200k_base`` is 3.6 MB. This
is a very small artifact standing between an air-gapped install and its first answer, which is
exactly why the failure it prevents was so confusing: an index built perfectly, and then a
connection error naming a blob store.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from manicule import vocabularies
from manicule.core.errors import ManiculeError
from manicule.vocabularies import bundle as bundles

PACKAGE_INIT = '''"""Offline tiktoken vocabularies for manicule, as package data.

Generated by ``tools/build_vocabulary_bundle.py``. The bundle beside this module carries BPE
vocabulary files fetched from the URLs its manifest records, with the digests tiktoken
declares for them. They are platform-independent text tables, so this distribution is valid on
any machine — but it is built rather than published, because manicule does not redistribute
files whose license terms it cannot state.
"""

from pathlib import Path

__all__ = ["bundle_root"]


def bundle_root() -> Path:
    """The bundle directory carried by this distribution."""
    return Path(__file__).parent / "bundle"
'''


def main(argv: list[str] | None = None) -> int:
    """Build the bundle. Returns a process exit status."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Directory to write the bundle into. Created if absent.",
    )
    parser.add_argument(
        "--encodings",
        nargs="+",
        default=None,
        help="Encodings to bundle. Defaults to the ones this install asks for: the chunker's "
        "stand-in, the context fitter's configured encoding and the generation budget's.",
    )
    parser.add_argument(
        "--prefetch",
        action="store_true",
        help="Fetch anything missing from the tiktoken cache first. Requires network access, "
        "and is opt-in so that a build cannot quietly become a download.",
    )
    parser.add_argument(
        "--package",
        action="store_true",
        help="Write an importable manicule_vocabularies package around the bundle, so it can "
        "be installed rather than copied.",
    )
    args = parser.parse_args(argv)

    try:
        encodings: list[str] = list(args.encodings or vocabularies.required_encodings())
        if args.prefetch:
            seeded = vocabularies.prefetch(encodings)
            print(f"seeded: {list(seeded)}")
        destination = Path(args.output)
        if args.package:
            destination = destination / "src" / bundles.BUNDLE_MODULE / "bundle"
        bundle = bundles.build(encodings, destination)
        if args.package:
            module = destination.parent
            (module / "__init__.py").write_text(PACKAGE_INIT, encoding="utf-8")
            (module / "py.typed").write_text("", encoding="utf-8")
    except ManiculeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    total = sum(entry.size for entry in bundle.vocabularies.values())
    print(f"bundle:   {bundle.root}")
    print(f"tiktoken: {bundle.tiktoken_version} (recorded, not required)")
    print(f"size:     {total / 1_000_000:.1f} MB across {len(bundle.vocabularies)} files")
    for name in bundle.encoding_names:
        print(f"  {name}")
        for url in bundle.encodings[name]:
            entry = bundle.vocabularies[url]
            print(f"    {url.rsplit('/', 1)[-1]:<28} {entry.sha256[:16]} {entry.size:>10}")
    return 0


if __name__ == "__main__":  # pragma: no cover - a script entry point
    raise SystemExit(main())
